### ISSUE TITLE
The save option is ambiguous in the extension configuration process.

### ISSUE THREAD

**Issue by joaocanuto** [ErnaneJ/tradingworks-plus#25]
When I click save on the settings tab, I don't get any alerts that the settings have been saved. In fact, I get an alert that notifications are disabled.
The situation is ambiguous because it seems that the configuration was not saved, as it does not allow messages

**Comment by ErnaneJ** [comment]
Hello Joao, I understand your problem and it really makes sense. If the user has checked the option to not receive messages then this shouldn't be seen as a problem. Thanks for the feedback. I will make a request to change this.

Regarding the alert regarding the information saving status, there is no input because the save button itself changes its text when clicked.

![image](https://user-images.githubusercontent.com/64796733/228670769-d5d72902-d45f-451b-a113-02db28479bdd.png)

Also, a notification message is sent, if notifications are enabled, in the browser and whatsapp via CallMeBot.

**Comment by ErnaneJ** [comment]
I will close this issue. This PR (#27) brings improvements in the control of messages by the user that possibly match your request.
